lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug SessionPlugs
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    get "/your", PageController, :your
    get "/created", PageController, :created
    get "/report", PageController, :report
    get "/profile", UserController, :profile
    get "/timeblocks", TaskController, :timeblocks
    get "/edittime", TaskController, :edittime
    put "/edittime", TaskController, :time
    resources "/users", UserController
    resources "/tasks", TaskController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
    resources "/timeblocks", TimeController, except: [:new, :edit]
  end
end

lib/tasktracker_web/templates/page/created.html.eex
<div class="row">
  <div class="col-md-9">
    <h2 class="display-4"> Tasks created by you </h2>
  </div>
  <div class="col-md-3">
    <div class="float-right">
    <%= link "Back", to: page_path(@conn, :feed), class: "btn-lg btn-secondary" %>
  </div>
</div>
</div>
<div class="p-3"></div>
<%= if length(Enum.filter(@tasks, fn(task) -> task.user.id == @current_user.id end)) != 0 do %>
<%= Enum.map @tasks, fn task -> %>
<%= if task.user.id == @current_user.id do %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-9">
            <h1 class="card-title"><%= task.title %></h1>
          </div>
          <div class="col-md-3">
            <div class="float-right">
              <%= if task.completed == false do %>
              <p class="btn btn-warning disabled">Not Completed</p>
              <% else %>
              <p class="btn btn-success disabled">Completed</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="font-weight-bold">
          <p class="card-subtitle mb-2 text-muted"> by <%= task.user.name %></p>
          <p class="card-subtitle mb-2 text-muted">This task is assigned to <%= task.assigned.name %></p>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= task.body %></p>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-9">
            <p>Time taken <%= task.time_taken %> minutes</p>
          </div>
          <div class="col-md-3">
            <%= if task.user.id == @current_user.id do %>
            <div class="float-right">
              <div class="btn-group">
                <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn-sm btn-secondary" %>
                <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn-sm btn-danger btn-xs" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-3"></div>
<% end %>
<% end %>
<% else %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h2> No tasks created by you </h2>
      </div>
    </div>
  </div>
</div>
<% end %>

lib/tasktracker_web/templates/page/feed.html.eex
<h1 class="display-1"> Task Trackr. </h1>
<div class="btn-group">
<%= link "Created Tasks", to: page_path(@conn, :created), class: "btn btn-secondary" %>
<%= link "Assigned Tasks", to: page_path(@conn, :your), class: "btn btn-secondary" %>
<%= link "Manage", to: user_path(@conn, :index), class: "btn btn-secondary" %>
<%= link "Profile", to: user_path(@conn, :profile), class: "btn btn-secondary" %>
<%= link "Reports", to: page_path(@conn, :report), class: "btn btn-secondary" %>
<%= link "Add Task", to: task_path(@conn, :new), class: "btn btn-primary"%>
</div>
<div class="p-3"></div>
<%= if length(@tasks) != 0 do %>
<%= Enum.map @tasks, fn task -> %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-9">
            <h1 class="card-title"><%= task.title %></h1>
          </div>
          <div class="col-md-3">
            <div class="float-right">
              <%= if task.completed == false do %>
              <p class="btn btn-warning disabled">Not Completed</p>
              <% else %>
              <p class="btn btn-success disabled">Completed</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="font-weight-bold">
          <p class="card-subtitle mb-2 text-muted"> by <%= task.user.name %></p>
          <p class="card-subtitle mb-2 text-muted">This task is assigned to <%= task.assigned.name %></p>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= task.body %></p>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-9">
          </div>
          <div class="col-md-3">
            <%= if task.user.id == @current_user.id || task.assigned.id == @current_user.id do %>
            <div class="float-right">
              <div class="btn-group">
                <%= link "Timeblocks", to: task_path(@conn, :timeblocks, taskid: task), class: "btn-sm btn-primary" %>
                <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn-sm btn-secondary" %>
                <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn-sm btn-danger" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-3"></div>
<% end %>
<% else %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h2> Nothing to show. Create a task by clicking on <span class="btn btn-primary">Add Task</span> button above </h2>
      </div>
    </div>
  </div>
</div>
<% end %>

lib/tasktracker_web/templates/page/index.html.eex
<div class="d-flex justify-content-center align-items-center">
  <h1 class="display-1"> Task Trackr. </h1>
</div>
<div class="p-3"></div>
<div class="d-flex justify-content-center align-items-center">
  <h1 class="display-5">Login</h1>
</div>
<div class="p-3"></div>
<div class="d-flex justify-content-center align-items-center">
  <%= form_tag("/session", method: :post) do %>
  <div class="form-group">
    <input type="text" name="name" placeholder="your name">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary btn-block">Login</button>
  </div>
  <div class="form-group">
    <%= link "Register", to: user_path(@conn, :new), class: "btn btn-secondary btn-block"%>
  </div>
  <% end %>
</div>

lib/tasktracker_web/templates/page/report.html.eex
<h1 class="display-4">Report</h1>
<%= link "Back", to: page_path(@conn, :feed), class: "btn btn-secondary" %>
<div class="p-3"></div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Task Title</th>
      <th>Status</th>
      <th>Assigned To</th>
    </tr>
  </thead>
  <tbody>
    <%= Enum.map @report, fn report -> %>
    <tr>
      <td><%= report.id %></td>
      <td><%= report.title %></td>
      <%= if report.completed == false do %>
      <td>Not Completed</td>
      <% else %>
      <td>Completed</td>
      <% end %>
      <td><%= report.assigned.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

lib/tasktracker_web/templates/page/your.html.eex
<div class="row">
  <div class="col-md-9">
    <h2 class="display-4"> Tasks assigned to you </h2>
  </div>
  <div class="col-md-3">
    <div class="float-right">
    <%= link "Back", to: page_path(@conn, :feed), class: "btn-lg btn-secondary" %>
  </div>
</div>
</div>
<div class="p-3"></div>
<%= if length(Enum.filter(@tasks, fn(task) -> task.assigned.id == @current_user.id end)) != 0 do %>
<%= Enum.map @tasks, fn task -> %>
<%= if task.assigned_id == @current_user.id do %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-9">
            <h1 class="card-title"><%= task.title %></h1>
          </div>
          <div class="col-md-3">
            <div class="float-right">
              <%= if task.completed == false do %>
              <p class="btn btn-warning disabled">Not Completed</p>
              <% else %>
              <p class="btn btn-success disabled">Completed</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="font-weight-bold">
          <p class="card-subtitle mb-2 text-muted"> by <%= task.user.name %></p>
          <p class="card-subtitle mb-2 text-muted">This task is assigned to <%= task.assigned.name %></p>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= task.body %></p>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-9">
            <p>Time taken <%= task.time_taken %> minutes</p>
          </div>
          <div class="col-md-3">
            <%= if task.user.id == @current_user.id do %>
            <div class="float-right">
              <div class="btn-group">
                <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn-sm btn-secondary" %>
                <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn-sm btn-danger btn-xs" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-3"></div>
<% end %>
<% end %>
<% else %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h2> No tasks assigned to you </h2>
      </div>
    </div>
  </div>
</div>
<% end %>